#server:
#  port: 8090
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8090/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 4000
#----------------------------------------------------------------------------------
server:
  port: 8090

spring:
  application:
    name: eureka-server